//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMONO {
    
    
    public partial class Default {
        
        protected System.Web.UI.WebControls.HyperLink userprofile;
        
        protected System.Web.UI.WebControls.HyperLink deconnexion;
        
        protected System.Web.UI.HtmlControls.HtmlForm form2;
        
        protected System.Web.UI.WebControls.TextBox exampleInputEmail1;
        
        protected System.Web.UI.WebControls.Label EmailError;
        
        protected System.Web.UI.WebControls.TextBox exampleInputPassword1;
        
        protected System.Web.UI.WebControls.Label passwordError;
        
        protected System.Web.UI.WebControls.CheckBox checkbox1;
        
        protected System.Web.UI.WebControls.Button connexion;
        
        protected System.Web.UI.WebControls.Panel panelOK;
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.Button button1;
    }
}
